<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="lixionggang-PC" name="192.168.56.101:5555" tests="1" failures="0" timestamp="26 Apr 2016 13:48:17 GMT" time="51.352" errors="0">
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="cn.crazy.appium.testcases.ZhihuLoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at cn.crazy.appium.testcases.ZhihuLoginTest.afterMethod(ZhihuLoginTest.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="@AfterClass afterTest" time="0.0" classname="cn.crazy.appium.testcases.ZhihuLoginTest">
    <skipped/>
  </testcase> <!-- @AfterClass afterTest -->
  <testcase name="login" time="0.001" classname="cn.crazy.appium.testcases.ZhihuLoginTest"/>
</testsuite> <!-- 192.168.56.101:5555 -->
